'use client';

import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { 
  Activity, 
  X, 
  TrendingUp, 
  MapPin, 
  Train, 
  Road, 
  Hospital, 
  GraduationCap, 
  ShieldCheck, 
  Sparkles, 
  Download, 
  CheckCircle2, 
  Award,
  Layers,
  BarChart3
} from 'lucide-react';
import { formatNumberIndian } from '../lib/utils';
import { AREA_MARKET_DATA } from '../data/areaMarketData';

export default function AIAreaAnalysisModal({ property, isOpen, onClose }) {
  const [mounted, setMounted] = useState(false);
  const [downloadSuccess, setDownloadSuccess] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  // Lock background page scroll so page stays stationary ("standed")
  useEffect(() => {
    if (!isOpen) return;

    const originalBodyOverflow = document.body.style.overflow;
    const originalBodyPaddingRight = document.body.style.paddingRight;
    const originalHtmlOverflow = document.documentElement.style.overflow;
    const scrollbarWidth = window.innerWidth - document.documentElement.clientWidth;

    if (scrollbarWidth > 0) {
      document.body.style.paddingRight = `${scrollbarWidth}px`;
    }
    document.body.style.overflow = 'hidden';
    document.documentElement.style.overflow = 'hidden';
    document.body.classList.add('modal-open');
    document.documentElement.classList.add('modal-open');

    const handleKeyDown = (e) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleKeyDown);

    return () => {
      document.body.style.overflow = originalBodyOverflow;
      document.body.style.paddingRight = originalBodyPaddingRight;
      document.documentElement.style.overflow = originalHtmlOverflow;
      document.body.classList.remove('modal-open');
      document.documentElement.classList.remove('modal-open');
      window.removeEventListener('keydown', handleKeyDown);
    };
  }, [isOpen, onClose]);

  if (!isOpen || !property || !mounted) return null;

  const areaId = property.id === 'prop-13' ? 'tambaram' :
    (property.address?.neighborhood?.toLowerCase().includes('tambaram') || property.address?.city?.toLowerCase().includes('tambaram')) ? 'tambaram' :
    property.address?.neighborhood?.toLowerCase().includes('omr') ? 'omr' :
    property.address?.neighborhood?.toLowerCase().includes('guindy') ? 'guindy' :
    property.address?.neighborhood?.toLowerCase().includes('ecr') ? 'ecr' : 'tambaram';

  const area = AREA_MARKET_DATA[areaId] || AREA_MARKET_DATA['tambaram'];

  const handleDownloadAnalysis = () => {
    try {
      const doc = `========================================================================\n` +
        `   JK REALTY ARTIFICIAL INTELLIGENCE AREA INTELLIGENCE REPORT         \n` +
        `   Micro-Market Demographic & Infrastructure Impact Audit              \n` +
        `========================================================================\n\n` +
        `CORRIDOR             : ${area.name} Micro-Market\n` +
        `ANALYSIS HEADLINE    : "${area.aiAnalysis.headline}"\n` +
        `CURRENT AVG RATE     : ₹${formatNumberIndian(area.currentAvgRateSqFt)} / Sq.Ft\n` +
        `1-YEAR CAPITAL GROWTH: +${area.oneYearGrowth}%\n` +
        `DEMAND LEVEL         : ${area.demandLevel} (${area.demandScore}/10 Score)\n` +
        `2028 TARGET FORECAST : ${area.aiAnalysis.targetPrice2028}\n` +
        `ESTIMATED VILLA YIELD: ${area.aiAnalysis.rentalYieldRange}\n` +
        `RISK ASSESSMENT      : ${area.aiAnalysis.riskScore}\n\n` +
        `INFRASTRUCTURE CATALYSTS TRACKED:\n` +
        area.futureDevelopments.map((d, i) => `${i + 1}. ${d.title} (${d.category}) - Impact: ${d.impactScore} - ETA: ${d.expectedCompletion}`).join('\n') +
        `\n\nDETAILED INTELLIGENCE INSIGHT:\n${area.aiAnalysis.detailedInsight}\n` +
        `========================================================================\n` +
        `Certified AI Area Intelligence Dossier • Generated by JK Realty\n`;

      const blob = new Blob([doc], { type: 'text/plain;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `AI_Area_Analysis_${areaId}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      setDownloadSuccess(true);
      setTimeout(() => setDownloadSuccess(false), 3000);
    } catch (e) {
      console.warn('Download error', e);
    }
  };

  return createPortal(
    <div role="dialog" aria-modal="true" className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/65 backdrop-blur-md p-3 sm:p-6 animate-in fade-in duration-300">
      <div className="relative w-full max-w-3xl max-h-[85vh] bg-white border-2 border-[#D4AF37]/50 rounded-3xl shadow-2xl flex flex-col overflow-hidden text-[#1F2937] my-auto">
        
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200 bg-[#FAF8F5] z-20">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-emerald-700 text-white flex items-center justify-center shadow-xs">
              <Activity className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <span className="text-xs font-black uppercase tracking-widest text-emerald-800">
                  Micro-Market Intelligence
                </span>
                <span className="px-2 py-0.5 rounded-full bg-[#1E3A5F]/10 text-[#1E3A5F] text-[10px] font-mono font-bold">
                  📍 {area.name}
                </span>
              </div>
              <h3 className="text-lg font-black text-[#1E3A5F] font-serif">
                AI Micro-Market Area Analysis
              </h3>
            </div>
          </div>

          <button
            onClick={onClose}
            className="p-2 rounded-xl bg-white hover:bg-gray-100 text-[#4B5563] hover:text-[#1E3A5F] border border-gray-200 transition-all shadow-xs"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 min-h-0 overflow-y-auto p-6 sm:p-8 space-y-6">
          
          {/* Executive AI Statement Card */}
          <div className="p-6 rounded-3xl bg-[#FAF8F5] border-2 border-[#D4AF37]/40 space-y-4 shadow-sm">
            <div className="flex items-center gap-2 text-xs font-black uppercase tracking-widest text-[#8A5A00]">
              <Sparkles className="w-4 h-4" />
              <span>AI Strategic Consensus</span>
            </div>
            <h4 className="text-xl sm:text-2xl font-black text-[#1E3A5F] font-serif leading-snug">
              &ldquo;{area.aiAnalysis.headline}&rdquo;
            </h4>
            <p className="text-xs sm:text-sm text-[#374151] leading-relaxed font-normal">
              {area.aiAnalysis.detailedInsight}
            </p>
          </div>

          {/* Key Intelligence Metrics Grid */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-xs">
            
            <div className="p-4 rounded-2xl bg-white border border-gray-200 shadow-xs space-y-1">
              <span className="text-[10px] font-mono uppercase text-gray-500 font-bold block">1-Yr Appreciation</span>
              <div className="text-xl font-black text-emerald-800 font-serif">
                +{area.oneYearGrowth}%
              </div>
              <span className="text-[10px] text-emerald-700 font-bold">High Momentum</span>
            </div>

            <div className="p-4 rounded-2xl bg-white border border-gray-200 shadow-xs space-y-1">
              <span className="text-[10px] font-mono uppercase text-gray-500 font-bold block">Demand Score</span>
              <div className="text-xl font-black text-[#1E3A5F] font-serif">
                {area.demandScore}<span className="text-xs font-normal text-gray-400">/10</span>
              </div>
              <span className="text-[10px] text-[#8A5A00] font-black">{area.demandLevel}</span>
            </div>

            <div className="p-4 rounded-2xl bg-white border border-gray-200 shadow-xs space-y-1">
              <span className="text-[10px] font-mono uppercase text-gray-500 font-bold block">2028 Price Target</span>
              <div className="text-base font-black text-emerald-800 font-mono">
                {area.aiAnalysis.targetPrice2028}
              </div>
              <span className="text-[10px] text-gray-500">Post-Metro Lift</span>
            </div>

            <div className="p-4 rounded-2xl bg-white border border-gray-200 shadow-xs space-y-1">
              <span className="text-[10px] font-mono uppercase text-gray-500 font-bold block">Villa Rental Yield</span>
              <div className="text-base font-black text-[#8A5A00] font-mono">
                {area.aiAnalysis.rentalYieldRange}
              </div>
              <span className="text-[10px] text-gray-500">Corporate Executive</span>
            </div>

          </div>

          {/* Infrastructure Catalysts List */}
          <div className="space-y-3">
            <h4 className="text-sm font-black uppercase tracking-wider text-[#1E3A5F] flex items-center gap-2">
              <Road className="w-4 h-4 text-[#8A5A00]" />
              <span>Upcoming High-Impact Infrastructure Projects</span>
            </h4>

            <div className="space-y-2.5">
              {area.futureDevelopments.map(dev => (
                <div key={dev.id} className="p-4 rounded-2xl bg-[#FAF8F5] border border-gray-200 flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs">
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <span className="px-2 py-0.5 rounded bg-blue-100 text-blue-800 text-[10px] font-bold uppercase font-mono">
                        {dev.category}
                      </span>
                      <span className="font-bold text-[#1E3A5F]">{dev.title}</span>
                    </div>
                    <p className="text-[11px] text-[#4B5563] max-w-xl">{dev.description}</p>
                  </div>

                  <div className="text-left sm:text-right shrink-0">
                    <span className="text-[11px] font-mono font-bold text-emerald-800 block">ETA: {dev.expectedCompletion}</span>
                    <span className="text-[10px] font-mono text-[#8A5A00] font-bold">{dev.impactScore}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Livability Matrix Footnote */}
          <div className="p-4 rounded-2xl bg-white border border-gray-200 shadow-xs space-y-2 text-xs">
            <span className="font-bold text-[#1E3A5F] uppercase tracking-wider text-[11px] block">
              Neighborhood Connectivity Matrix
            </span>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-[11px] text-[#4B5563]">
              <div className="flex items-center gap-1.5 font-medium">
                <Train className="w-3.5 h-3.5 text-[#8A5A00]" />
                <span>Tambaram Stn: 3.0 km</span>
              </div>
              <div className="flex items-center gap-1.5 font-medium">
                <Road className="w-3.5 h-3.5 text-[#8A5A00]" />
                <span>GST Bypass: 800 m</span>
              </div>
              <div className="flex items-center gap-1.5 font-medium">
                <Hospital className="w-3.5 h-3.5 text-rose-600" />
                <span>AIIMS Referral: 2.1 km</span>
              </div>
              <div className="flex items-center gap-1.5 font-medium">
                <GraduationCap className="w-3.5 h-3.5 text-blue-600" />
                <span>MCC College: 1.8 km</span>
              </div>
            </div>
          </div>

        </div>

        {/* Footer Actions */}
        <div className="flex flex-col sm:flex-row items-center justify-between gap-3 px-6 py-4 border-t border-gray-200 bg-[#FAF8F5]">
          <span className="text-xs text-[#4B5563] font-mono">
            {downloadSuccess ? '✓ Area Intelligence Dossier Exported' : 'Export Official Area Dossier'}
          </span>
          
          <div className="flex items-center gap-2.5 w-full sm:w-auto">
            <button
              onClick={handleDownloadAnalysis}
              className="flex-1 sm:flex-none px-4 py-2.5 rounded-xl bg-[#FAF8F5] hover:bg-gray-100 text-[#1E3A5F] border border-gray-300 text-xs font-bold flex items-center justify-center gap-1.5 transition-all shadow-xs"
            >
              <Download className="w-3.5 h-3.5 text-[#8A5A00]" />
              <span>Download Area Report</span>
            </button>

            <button
              onClick={onClose}
              className="flex-1 sm:flex-none px-5 py-2.5 rounded-xl bg-[#1E3A5F] hover:bg-[#162c48] text-white text-xs font-bold transition-all shadow-md"
            >
              Close
            </button>
          </div>
        </div>

      </div>
    </div>,
    document.body
  );
}
